POST http://localhost:8000/api
Content-Type: application/json

{
    "message": "Ceci est un message d'un client vers le server"
}

###
GET http://localhost:8000/api

###
PUT http://localhost:8000/api
Content-Type: application/json

{
    "old_message": "test2",
    "new_message": "test3"
}

###
DELETE http://localhost:8000/api
Content-Type: application/json

{
    "message": "test3"
}