titres = [
    "",
    "",
    "",
    "Music Recorder\\music\\AC DC BEST OFF",
    " <<artiste>>:ACDC",
    "",
    "Aint No Fun (Waiting Around to Be a Millionaire) (Original Australian Release)",
    "All Screwed Up",
    "Anything Goes",
    "Are You Ready",
    "Back In Black",
    "Bad Boy Boogie",
    "Badlands",
    "Big Balls",
    "Big Gun",
    "Big Jack",
    "Black Ice",
    "Come and Get It",
    "Demon Fire",
    "Dirty Deeds Done Dirt Cheap",
    "For Those About to Rock (We Salute You)",
    "Hells Bells",
    "Highway to Hell",
    "If You Want Blood You Got It (Demo)",
    "Its a Long Way to the Top (If You Wanna Rock N Roll)",
    "Let There Be Rock",
    "Play Ball.mp3",
    "Problem Child",
    "Ride On",
    "Rock N Roll Damnation",
    "Rock N Roll Train",
    "Rock or Bust.mp3",
    "Shoot to Thrill",
    "Shot In The Dark",
    "Sin City",
    "Stiff Upper Lip",
    "T.N.T_",
    "The Jack",
    "Thunderstruck",
    "War Machine",
    "Whole Lotta Rosie",
    "You Shook Me All Night Long",
    "",
    "Music Recorder\\music\\Alanis Morissette Ironic",
    " <<artiste>>:Alanis Morissette",
    "",
    "01 All I Really Want (2015 Remaster)",
    "02 You Oughta Know (2015 Remaster)",
    "03 Perfect (2015 Remaster)",
    "04 Hand in My Pocket (2015 Remaster)",
    "05 Right Through You (2015 Remaster)",
    "06 Forgiven (2015 Remaster)",
    "07 You Learn (2015 Remaster)",
    "08 Head over Feet (2015 Remaster)",
    "09 Mary Jane (2015 Remaster)",
    "10 Ironic (2015 Remaster)",
    "11 Not the Doctor (2015 Remaster)",
    "12 Wake Up (2015 Remaster)",
    "13 You Oughta Know (Jimmy the Saint Blend) _ Your House (A Capella) [2015 Remaster]",
    "",
    "Music Recorder\\music\\Alphaville Forever Young",
    " <<artiste>>:Alphaville",
    "",
    "01 A Victory of Love",
    "02 Summer in Berlin",
    "03 Big in Japan",
    "04 To Germany With Love",
    "05 Fallen Angel",
    "06 Forever Young",
    "07 In the Mood",
    "08 Sounds Like a Melody",
    "09 Lies",
    "10 The Jet Set",
    "",
    "Music Recorder\\music\\Ballades Rock",
    " <<artiste>>:Divers_artistes",
    "",
    "Alone",
    "Aucun express",
    "Ballade pour Roger",
    "Best of You",
    "Bijou bijou (Remix 1992)",
    "Carrie",
    "Dust in the Wind",
    "Every Breath You Take",
    "Forever",
    "Home Sweet Home",
    "I Cant Tell You Why (2013 Remaster)",
    "I Dont Want to Miss a Thing (From _Armageddon_ Soundtrack)",
    "I Need You Tonight (2008 Remaster)",
    "In The Air Tonight (2015 Remastered)",
    "Iris",
    "Is This Love (2003 Remaster)",
    "LEnfant de la lune",
    "La bombe humaine (Remasteris  en 2015)",
    "La vie est peut- tre belle",
    "Mama, Im Coming Home",
    "More Than Words",
    "Never Say Goodbye",
    "Nothing Else Matters",
    "November Rain",
    "Open Arms",
    "Still Loving You",
    "The Flame",
    "The Sound of Silence",
    "The Story",
    "Under the Bridge",
    "Voil  cest fini",
    "Waiting for a Girl like You",
    "Who Wants To Live Forever (Remastered 2011)",
    "With Or Without You",
    "  ma place",
    "",
    "Music Recorder\\music\\Beatles Let it be",
    " <<artiste>>:Beatles",
    "",
    "01 Two Of Us (Remastered 2009)",
    "02 Dig A Pony (Remastered 2009)",
    "03 Across The Universe (Remastered 2009)",
    "04 I Me Mine (Remastered 2009)",
    "05 Dig It (Remastered 2009)",
    "06 Let It Be (Remastered 2009)",
    "07 Maggie Mae (Remastered 2009)",
    "08 Ive Got A Feeling (Remastered 2009)",
    "09 One After 909 (Remastered 2009)",
    "10 The Long And Winding Road (Remastered 2009)",
    "11 For You Blue (Remastered 2009)",
    "12 Get Back (Remastered 2009)",
    "",
    "Music Recorder\\music\\Beatles Revolver",
    " <<artiste>>:Beatles",
    "",
    "01 Taxman (Remastered 2009)",
    "02 Eleanor Rigby (Remastered 2009)",
    "03 Im Only Sleeping (Remastered 2009)",
    "04 Love You To (Remastered 2009)",
    "05 Here, There And Everywhere (Remastered 2009)",
    "06 Yellow Submarine (Remastered 2009)",
    "07 She Said She Said (Remastered 2009)",
    "08 Good Day Sunshine (Remastered 2009)",
    "09 And Your Bird Can Sing (Remastered 2009)",
    "10 For No One (Remastered 2009)",
    "11 Doctor Robert (Remastered 2009)",
    "12 I Want To Tell You (Remastered 2009)",
    "13 Got To Get You Into My Life (Remastered 2009)",
    "14 Tomorrow Never Knows (Remastered 2009)",
    "",
    "Music Recorder\\music\\Bee Gees Saturday Night Fever",
    " <<artiste>>:Bee Gees",
    "",
    "01 Stayin Alive",
    "02 How Deep Is Your Love",
    "03 Night Fever (From _Saturday Night Fever_ Soundtrack)",
    "04 More Than A Woman",
    "05 If I Cant Have You",
    "06 A Fifth Of Beethoven",
    "07 More Than A Woman",
    "08 Manhattan Skyline",
    "09 Calypso Breakdown",
    "10 Night On Disco Mountain",
    "11 Open Sesame",
    "12 Jive Talkin",
    "13 You Should Be Dancing",
    "14 Boogie Shoes",
    "15 Salsation",
    "16 Disco Inferno",
    "",
    "Music Recorder\\music\\Benabar Best Of",
    " <<artiste>>:Benabar",
    "",
    "01 Le d ner",
    "02 Tu peux compter sur moi",
    "03 Quatre Murs Et Un Toit (Nouvelle Version)",
    "04 Maritie et Gilbert Carpentier",
    "05 La berceuse",
    "06 Les  pices du souk du Caire",
    "07 Je suis de celles",
    "08 Dis-lui oui",
    "09 Monospace",
    "10 Sac   main",
    "11 Litin raire",
    "12 Ya Une Fille Quhabite Chez Moi",
    "13 Bon anniversaire",
    "14 A notre sant ",
    "15 Porcelaine",
    "16 V lo",
    "17 Majorette",
    "18 La ptite monnaie",
    "19 Adolescente (Version 2007)",
    "20 La pierrade",
    "",
    "Music Recorder\\music\\Bernard Lavillier concert 1980",
    " <<artiste>>:Bernard Lavillier",
    "",
    "01 Rock City (Live)",
    "02 Capoiera (Live)",
    "03 Attention Fragile (Live)",
    "04 Traffic (Live)",
    "05 Urubus (Live)",
    "06 Fortaleza (Live)",
    "07 La Salsa (Live)",
    "08 Kingston (Live)",
    "09 Spinnaker (Live)",
    "10 Fuckin Life (Live)",
    "11 Pierrot La Lame (Live)",
    "12 Sertao (Live)",
    "13 Promenade Des Anglais (Live)",
    "14 Les Fun railles Du Voyeur (Live)",
    "15 La Danseuse Du Sud (Live)",
    "16 Bats-Toi (Live)",
    "17 NAppartiens Jamais A Personne (Live)",
    "18 Heart Beat (Live)",
    "19 Fauve DAmazone (Live)",
    "20 La Musique (Live)",
    "",
    "Music Recorder\\music\\Blues La grande Anthologie",
    " <<artiste>>:Divers_artistes blues",
    "",
    "01 Katy Crossing Blues",
    "02 Screaming and Crying Blues",
    "03 Down South Blues",
    "04 Blues Before Sunrise",
    "05 Poor Mans Friend",
    "06 Harmonica and Washboard Breakdown",
    "07 Viola Lee Blues",
    "08 Strange Place Blues",
    "09 It Aint What You Usta Be",
    "10 Cold Blooded Murder N  2",
    "11 Brown Skin Girls",
    "12 Crying Mother Blues",
    "13 44 Blues",
    "14 New Come Back Baby",
    "15 Henry Brown Blues",
    "16 Tired of Your Line of Jive",
    "17 Down in Boogie Alley",
    "18 Kidnappers Blues",
    "19 Broke Man Blues",
    "20 Sweet Home Chicago",
    "21 Mean Mistreater Blues",
    "22 Hard Times Blues",
    "23 The St. Louis Blues",
    "24 2_19 Blues",
    "25 Shake the Boogie",
    "26 Thats All Right",
    "27 I Cant Get Along with You",
    "28 Blue Evening Blues",
    "29 Ive Been Treated Wrong",
    "30 Reckless Life Blues",
    "31 Im Gonna Leave You on the Outskirts of Town",
    "32 Midnight Steppers",
    "33 Down the Road Apiece",
    "34 Call It Stormy Monday",
    "35 Evil Gal Blues",
    "36 Thinkin and Worryin",
    "37 Dimples",
    "38 I Wish You Would",
    "39 Big Boss Man",
    "40 Reconsider Baby",
    "41 Im Your Hoochie Coochie Man",
    "42 Juke",
    "43 You Dont Love Me",
    "44 Smokestack Lightnin",
    "45 I Dont Know",
    "46 The Sky Is Crying",
    "47 Blues at Midnight",
    "48 Ten Years Ago",
    "",
    "Music Recorder\\music\\Bonamassa Dont Explain",
    " <<artiste>>:Joe Bonamassa",
    "",
    "01 Sinners Prayer",
    "02 Chocolate Jesus",
    "03 Your Heart Is As Black As Night",
    "04 For My Friends",
    "05 Dont Explain",
    "06 Id Rather Go Blind",
    "07 Somethings Got A Hold On Me",
    "08 Ill Take Care Of You",
    "09 Well, Well",
    "10 Aint No Way",
    "",
    "Music Recorder\\music\\Bonamassa You and Me",
    " <<artiste>>:Joe Bonamassa",
    "",
    "01 High Water Every Where",
    "01 Twenty-Four Hour Blues (Live At The Hollywood Bowl With Orchestra)",
    "02 Bridge to Better Days",
    "03 Asking Around for You",
    "04 So Many Roads",
    "05 I Dont Believe",
    "06 Tamp Em Up Solid",
    "07 Django",
    "08 Tea For One",
    "09 Palm Trees Helicopters and Gasoline",
    "10 Your Funeral and My Trial",
    "11 Torn Down",
    "",
    "Music Recorder\\music\\Canned Heat Best Of",
    " <<artiste>>:Canned Heat",
    "",
    "01 On The Road Again (Remastered 2005)",
    "02 Going Up The Country (Remastered 2005)",
    "03 Amphetamine Annie (Remastered)",
    "04 Rollin And Tumblin (Live At Monterey Pop Jazz Festival _ 1967)",
    "05 Dust My Broom (Live At Monterey Pop Jazz Festival _ 1967)",
    "06 Bullfrog Blues (Live At Monterey Pop Jazz Festival _ 1967)",
    "07 Henrys Shuffle",
    "08 Fried Hockey Boogie (Remastered 2005)",
    "09 Same All Over (Remastered 2005)",
    "10 Time Was (Remastered 2005)",
    "11 Low Down (And High Up) (Remastered 2005)",
    "12 Poor Moon (Remastered 2005)",
    "13 Lets Work Together (Remastered 2005)",
    "14 Future Blues (Remastered)",
    "15 Human Condition (Remastered 2005)",
    "16 Whiskey And Wimmen (Remastered 2005)",
    "17 Long Way From L.A. (Remastered 2005)",
    "18 Rockin With The King (Remastered)",
    "19 Rock & Roll Music (Remastered 2005)",
    "",
    "Music Recorder\\music\\canned Heat On The road Again",
    " <<artiste>>:Canned Heat",
    "",
    "01 On the Road Again (Live)",
    "02 Time Was (Live)",
    "03 Dont Know Where She Went (She Split) (Live)",
    "04 Nighthawk (Live)",
    "05 So Sad (The Worlds in a Tangle) (Live)",
    "06 Going up the Country (Live)",
    "07 Oaxaca (Live)",
    "08 Chicken Shack Boogie (Live)",
    "09 Future Blues (Live)",
    "10 Cristo Redentor (Live)",
    "11 Amphetamine Annie (Live)",
    "12 Rollin and Tumblin (Live)",
    "13 Lets Work Together (Live)",
    "14 Euro Boogie (Live)",
    "",
    "Music Recorder\\music\\CASH American IV The Man Comes Around",
    " <<artiste>>:Johny Cash",
    "",
    "01 The Man Comes Around",
    "02 Hurt",
    "03 Give My Love To Rose (Album Version)",
    "04 Bridge Over Troubled Water (Album Version)",
    "05 I Hung My Head",
    "06 First Time Ever I Saw Your Face (Album Version)",
    "07 Personal Jesus (Album Version)",
    "08 In My Life (Album Version)",
    "09 Sam Hall (Album Version)",
    "10 Danny Boy (Album Version)",
    "11 Desperado (Album Version)",
    "12 Im So Lonesome I Could Cry (Album Version)",
    "13 Tear Stained Letter (Album Version)",
    "14 Streets Of Laredo (Album Version)",
    "15 Well Meet Again",
    "",
    "Music Recorder\\music\\Cat Stevens Greatesthits",
    " <<artiste>>:Cat Stevens",
    "",
    "01 Wild World",
    "02 Oh Very Young",
    "03 Cant Keep It In",
    "04 Hard Headed Woman",
    "05 Moonshadow",
    "06 Two Fine People",
    "07 Peace Train",
    "08 Ready",
    "09 Father And Son",
    "10 Sitting",
    "11 Morning Has Broken",
    "12 Another Saturday Night",
    "",
    "Music Recorder\\music\\CCR Best Of",
    " <<artiste>>:CCR",
    "",
    "01 Bad Moon Rising (Remastered 1985)",
    "02 Born On The Bayou",
    "03 Proud Mary",
    "04 Travelin Band",
    "05 Have You Ever Seen The Rain",
    "06 Green River (Remastered 1985)",
    "07 Down On The Corner",
    "08 Lodi (Remastered 1985)",
    "09 Fortunate Son",
    "10 Lookin Out My Back Door",
    "11 Run Through The Jungle",
    "12 I Put A Spell On You",
    "13 Susie Q (Pt. 2)",
    "14 Sweet Hitch-Hiker",
    "15 It Came Out Of The Sky",
    "16 Wholl Stop The Rain",
    "17 I Heard It Through The Grapevine (Edit)",
    "18 Hey Tonight",
    "19 Cotton Fields (The Cotton Song)",
    "20 Long As I Can See The Light",
    "21 Molina",
    "22 Hello Mary Lou",
    "23 The Midnight Special",
    "24 Up Around The Bend",
    "",
    "Music Recorder\\music\\Chansons francaises",
    " <<artiste>>:Divers_artistes",
    "",
    "Andy (Folamours Italo Remix).mp3",
    "Belle- le-en-Mer, Marie-Galante.mp3",
    "Bon anniversaire.mp3",
    "Bonnie And Clyde.mp3",
    "Cest  crit.mp3",
    "Cour de loup.mp3",
    "Du rhum, des femmes.mp3",
    "Eve l ve-toi.mp3",
    "Foule sentimentale.mp3",
    "Il faudra leur dire.mp3",
    "Il jouait du piano debout (Remasteris  en 2004).mp3",
    "Il me dit que je suis belle.mp3",
    "Il tape sur des bambous.mp3",
    "Je suis venu te dire que je men vais.mp3",
    "Joue pas.mp3",
    "Joy.mp3",
    "Lamour   la machine.mp3",
    "Leffet papillon.mp3",
    "La rivi re de notre enfance [feat. Garou].mp3",
    "Le d ner.mp3",
    "Ma libert  de penser.mp3",
    "Manhattan-Kaboul.mp3",
    "Martiniquaise.mp3",
    "Mea Culpa.mp3",
    "Pas de boogie woogie.mp3",
    "Plus pr s des  toiles.mp3",
    "Principles Of Lust_ Sadeness _ Find Love _ Sadeness (Reprise).mp3",
    "Quelque chose de Tennessee.mp3",
    "Sang pour sang.mp3",
    "Seul.mp3",
    "Sous le vent.mp3",
    "The Voice Of Enigma.mp3",
    "Zen.mp3",
    "  nos souvenirs.mp3",
    "",
    "Music Recorder\\music\\Chill Classic Rock",
    " <<artiste>>:Divers_artistes",
    "",
    "(Dont Fear) The Reaper",
    "1979 (Remastered 2012)",
    "A Horse with No Name",
    "A Whiter Shade of Pale (2007 Remaster)",
    "Afternoon Delight",
    "Against The Wind",
    "All Right Now",
    "American Pie",
    "Bad Company (2009 Remaster)",
    "Beast Of Burden (Remastered 1994)",
    "Bed Of Roses",
    "Behind Blue Eyes (Remastered 2022)",
    "Black Magic Woman _ Gypsy Queen",
    "Brass in Pocket (2018 Remaster)",
    "Brothers In Arms (Remastered 1996)",
    "Cant You See",
    "Carry On",
    "Cats in the Cradle",
    "Cocaine",
    "Come and Get Your Love (Single Version)",
    "Comfortably Numb (2011 Remastered Version)",
    "Cool Cat (Remastered 2011)",
    "Crazy Love (2013 Remaster)",
    "Dancing In The Moonlight",
    "Dream On",
    "Dream Weaver",
    "Dust in the Wind",
    "Every Breath You Take",
    "Every Little Thing She Does Is Magic",
    "Everything I Own",
    "Fire and Rain",
    "Fly Like An Eagle",
    "For What Its Worth",
    "Give A Little Bit",
    "Glycerine (Remastered)",
    "God Only Knows (Mono)",
    "Going to California (Remaster)",
    "Going Up The Country",
    "Good Riddance (Time of Your Life)",
    "Harvest Moon",
    "Have You Ever Seen The Rain",
    "Heart of Gold (2009 Remaster)",
    "Hunger Strike",
    "Into the Mystic (2013 Remaster)",
    "Knockin On Heavens Door",
    "Landslide",
    "Lay, Lady, Lay",
    "Layla (Acoustic; Live at MTV Unplugged, Bray Film Studios, Windsor, England, UK, 1_16_1992; 1999 Remaster)",
    "Let It Be (Remastered 2009)",
    "Lifes Been Good",
    "Lightning Crashes",
    "Lights",
    "Listen to the Music",
    "Lookin Out My Back Door",
    "Losing My Religion",
    "Lyin Eyes (2013 Remaster)",
    "Maggie May",
    "Mary Janes Last Dance",
    "Me and Bobby McGee",
    "Midnight Rider",
    "Mr. Blue Sky",
    "My Best Friends Girl",
    "My Sweet Lord (2009 Remaster)",
    "Now And Then",
    "Ooh La La",
    "Pale Blue Eyes",
    "Patience",
    "Plush (Acoustic)",
    "Rhiannon",
    "Rich Girl",
    "Riders on the Storm",
    "Right Down the Line",
    "Rocket Man (I Think Its Going To Be A Long, Long Time)",
    "She Talks To Angels",
    "Shes A Rainbow",
    "Simple Man",
    "Solsbury Hill",
    "Sultans Of Swing",
    "Sundown",
    "Take It Easy (2013 Remaster)",
    "The Joker (Remastered 2017)",
    "The Kids Are Alright (Mono Version)",
    "The Pretender",
    "The River",
    "The Sound of Silence (Electric Version)",
    "The Weight (Remixed 2018)",
    "Time In A Bottle",
    "Time of the Season (Mono Version)",
    "Turn The Page (Live In Detroit_1975)",
    "Under Pressure (1994 Remastered Version)",
    "Ventura Highway",
    "Walk On the Wild Side",
    "What Its Like",
    "Whiskey In The Jar",
    "White Rabbit",
    "Wild World (Remastered 2020)",
    "Wildflowers",
    "Wish You Were Here",
    "With Or Without You",
    "Yellow Ledbetter",
    "",
    "Music Recorder\\music\\Christopher Cross Sailing",
    " <<artiste>>:Christopher Cross",
    "",
    "01 Say Youll Be Mine",
    "02 I Really Dont Know Anymore",
    "03 Spinning",
    "04 Never Be the Same",
    "05 Poor Shirley",
    "06 Ride Like the Wind",
    "07 The Light Is On",
    "08 Sailing",
    "09 Minstrel Gigolo",
    "",
    "Music Recorder\\music\\Clapton Unpluged",
    " <<artiste>>:Eric Clapton",
    "",
    "01 Signe (Acoustic Live)",
    "02 Before You Accuse Me (Acoustic Live)",
    "03 Hey Hey (Acoustic Live)",
    "04 Tears in Heaven (Acoustic Live)",
    "05 Lonely Stranger (Acoustic Live)",
    "06 Nobody Knows You When Youre Down and Out (Acoustic Live)",
    "07 Layla (Acoustic Live)",
    "08 Running on Faith (Acoustic Live)",
    "09 Walkin Blues (Acoustic Live)",
    "10 Alberta (Acoustic Live)",
    "11 San Francisco Bay Blues (Acoustic Live)",
    "12 Malted Milk (Acoustic Live)",
    "13 Old Love (Acoustic Live)",
    "14 Rollin & Tumblin (Acoustic Live)",
    "15 Circus",
    "16 My Fathers Eyes (Take 1)",
    "17 Running on Faith (Take 1)",
    "18 Walkin Blues (Take 1)",
    "19 My Fathers Eyes (Take 2)",
    "20 Worried Life Blues",
    "",
    "Music Recorder\\music\\compilation soir",
    " <<artiste>>:Divers_artistes",
    "",
    "(Theme From) Midnight Express",
    "1492 Christophe Colomb _ Conquest of the Paradise",
    "7 Seconds",
    "A Horse with No Name",
    "Alone Again (Naturally)",
    "Always Remember Us This Way",
    "Back To Black",
    "Berlin",
    "Blue Spanish Sky",
    "Blues Boys Tune (Album Version)",
    "Brothers In Arms (Remastered 1996)",
    "Calling You (Bagdad Cafe_Soundtrack Version)",
    "Chanson pour Pierrot",
    "Chopin_ 24 Pr ludes, Op. 28 - No. 4 in E Minor",
    "Come Away With Me",
    "Comptine dun autre  t , lapr s-midi",
    "Cristo Redentor (Live)",
    "C zanne peint",
    "Diego libre dans sa t te",
    "Dont Give Up",
    "Dont It Make My Brown Eyes Blue",
    "Dont Know Why",
    "Drive",
    "Dust In The Wind",
    "Eternal Flame",
    "Everybody Hurts",
    "Fallin",
    "Father and Son",
    "Feel",
    "Fields Of Gold (New Version)",
    "Follow You Follow Me (2007 Remaster)",
    "Forever Young",
    "Gnossienne No. 1",
    "Going to California (Remaster)",
    "Hallelujah (Radio Edit)",
    "Hands",
    "Harvest Moon",
    "Heart of Gold (2009 Remaster)",
    "Here It Is",
    "Hors-saison (Remastered)",
    "Hotel California (2013 Remaster)",
    "Hurt",
    "I Cant Tell You Why (2013 Remaster)",
    "Id Rather Go Blind",
    "Ill Take Care Of You",
    "If I Aint Got You",
    "Its Probably Me",
    "J cume",
    "Je dis aime",
    "Jezebel",
    "Jimmy",
    "Jojo",
    "La complainte du phoque en Alaska (Edition Remix e)",
    "La nuit je mens",
    "La Valse Dam lie",
    "La vie Th odore",
    "La wally",
    "Landslide",
    "Le Baiser.mp3",
    "Le paradis blanc (Remasteris  en 2002)",
    "Le sud",
    "Le vent nous portera",
    "Les mots bleus",
    "Les passantes (Live)",
    "Lullaby (Remastered)",
    "Ma r v rence",
    "Me & MRS. Jones",
    "Mother Shoots",
    "Mozart_ Piano Concerto No. 23 in A Major, K. 488 - II. Adagio",
    "My My, Hey Hey (Out of the Blue) [2016 Remaster]",
    "No Ordinary Love",
    "Nocturnes, Op. 9_ I. Larghetto en Si B mol Mineur",
    "Nothing Else Matters",
    "On the Beach",
    "One",
    "Out on the Weekend",
    "Paradis Perdus",
    "Part Two - A Murmuration of Starlings",
    "Part Two - In My Own Way",
    "Poor Mans Moody Blues",
    "Pour me comprendre (Remasteris  en 2008)",
    "Puisque tu pars",
    "Purple Rain (From _Super Bowl 41 Halftime Show_)",
    "Redemption Song",
    "Riders on the Storm",
    "Sad Lisa",
    "Sailing",
    "Samba Pa Ti",
    "Same Old Blues",
    "Sarah (et pr lude de Sarah)",
    "Satie_ Gymnopedie",
    "Scarborough Fair _ Canticle",
    "Seasons In The Sun",
    "Shape Of My Heart (My Songs Version)",
    "Shine On You Crazy Diamond, Pts. 1-5 (2011 Remaster).mp3",
    "Skyfall",
    "Sloe Gin",
    "Slow Dancing in a Burning Room (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "So Far Away from L.A_",
    "So Many Roads",
    "Steer Your Way",
    "Still Got The Blues",
    "Streets of Philadelphia",
    "Talk To Me (Live)",
    "Tears in Heaven",
    "The Ballad Of Lucy Jordan",
    "The Boxer",
    "The Great Gig In The Sky (2011 Remastered Version).mp3",
    "The Lady In Red",
    "The Sound of Silence (Electric Version)",
    "The Things You Said",
    "Torero",
    "True Colors",
    "Truman Sleeps",
    "Turn Me On",
    "T\xa0rrega_ Recuerdos de la Alhambra",
    "Un homme heureux",
    "Video Games",
    "We Are The Champions (Remastered 2011)",
    "What A Wonderful World",
    "When Youre Gone",
    "White Flag",
    "Wicked Game",
    "Wind Of Change",
    "Wonderful Life",
    "Wonderful Life_1",
    "",
    "Music Recorder\\music\\Deep Purple In Rock",
    " <<artiste>>:Deep Purple",
    "",
    "01 Speed King (1995 Remaster)",
    "02 Bloodsucker (1995 Remaster)",
    "03 Child in Time (1995 Remaster)",
    "04 Flight of the Rat (1995 Remaster)",
    "05 Into the Fire (1995 Remaster)",
    "06 Living Wreck (1995 Remaster)",
    "07 Hard Lovin Man (1995 Remaster)",
    "08 Black Night (1995 Remaster)",
    "09 Studio Chat 1",
    "10 Speed King (Piano Version)",
    "11 Studio Chat 2",
    "12 Cry Free (Roger Glover Remix)",
    "13 Studio Chat 3",
    "14 Jam Stew (Instrumental)",
    "15 Studio Chat 4",
    "16 Flight of the Rat (Roger Glover Remix)",
    "17 Studio Chat 5",
    "18 Speed King (Roger Glover Remix)",
    "19 Studio Chat 6",
    "20 Black Night (Roger Glover Remix)",
    "",
    "Music Recorder\\music\\Depeche mode Music for the Masses",
    " <<artiste>>:Depeche Mode",
    "",
    "01 Never Let Me Down Again",
    "02 The Things You Said",
    "03 Strangelove",
    "04 Sacred",
    "05 Little 15",
    "06 Behind the Wheel",
    "07 I Want You Now",
    "08 To Have and to Hold",
    "09 Nothing",
    "10 Pimpf",
    "11 Agent Orange",
    "12 Never Let Me Down Again (Aggro Mix)",
    "13 To Have and to Hold (Spanish Taster)",
    "14 Pleasure, Little Treasure (Glitter Mix)",
    "15 Pleasure, Little Treasure",
    "16 Route 66",
    "17 Stjarna",
    "18 Sonata No.14 in C#m (Moonlight Sonata)",
    "",
    "Music Recorder\\music\\Dire Straits Brother in arms",
    " <<artiste>>:Dire Straits",
    "",
    "",
    "01 So Far Away (Remastered 1996)",
    "02 Money For Nothing (Remastered 1996)",
    "03 Walk Of Life (Remastered 1996)",
    "04 Your Latest Trick (Remastered 1996)",
    "05 Why Worry_ (Remastered 1996)",
    "06 Ride Across The River (Remastered 1996)",
    "07 The Mans Too Strong (Remastered 1996)",
    "08 One World (Remastered 1996)",
    "09 Brothers In Arms (Remastered 1996)",
    "",
    "Music Recorder\\music\\Dire Straits Communiqu ",
    " <<artiste>>:Dire Straits",
    "",
    "",
    "01 Once Upon A Time In The West",
    "02 News",
    "03 Where Do You Think Youre Going_",
    "04 Communiqu ",
    "05 Lady Writer",
    "06 Angel Of Mercy",
    "07 Portobello Belle",
    "08 Single Handed Sailor",
    "09 Follow Me Home",
    "",
    "Music Recorder\\music\\Dire Straits Love Over Gold",
    " <<artiste>>:Dire Straits",
    "",
    "01 Telegraph Road",
    "02 Private Investigations",
    "03 Industrial Disease",
    "04 Love Over Gold",
    "05 It Never Rains",
    "",
    "Music Recorder\\music\\Dire Straits Sutans Of Swing",
    " <<artiste>>:Dire Straits",
    "",
    "",
    "01 Down To The Waterline",
    "02 Water Of Love",
    "03 Setting Me Up",
    "04 Six Blade Knife",
    "05 Southbound Again",
    "06 Sultans Of Swing",
    "07 In The Gallery",
    "08 Wild West End",
    "09 Lions",
    "",
    "Music Recorder\\music\\Dire Straits Tunnel Of Love",
    " <<artiste>>:Dire Straits",
    "",
    "01 Tunnel Of Love",
    "02 Romeo And Juliet",
    "03 Skateaway",
    "04 Expresso Love",
    "05 Hand In Hand",
    "06 Solid Rock",
    "07 Les Boys",
    "",
    "Music Recorder\\music\\Eagles Hotel California",
    " <<artiste>>:Eagles",
    "",
    "01 Hotel California (2013 Remaster)",
    "02 New Kid in Town (2013 Remaster)",
    "03 Life in the Fast Lane (2013 Remaster)",
    "04 Wasted Time (2013 Remaster)",
    "05 Wasted Time (Reprise) [2013 Remaster]",
    "06 Victim of Love (2013 Remaster)",
    "07 Pretty Maids All in a Row (2013 Remaster)",
    "08 Try and Love Again (2013 Remaster)",
    "09 The Last Resort (2013 Remaster)",
    "",
    "Music Recorder\\music\\Fleetwood Mac Rumours",
    " <<artiste>>:Fleetwood Mac",
    "",
    "01 Second Hand News (2004 Remaster)",
    "02 Dreams (2004 Remaster)",
    "03 Never Going Back Again (2004 Remaster)",
    "04 Dont Stop (2004 Remaster)",
    "05 Go Your Own Way (2004 Remaster)",
    "06 Songbird (2004 Remaster)",
    "07 The Chain (2004 Remaster)",
    "08 You Make Loving Fun (2004 Remaster)",
    "09 I Dont Want to Know (2004 Remaster)",
    "10 Oh Daddy (2004 Remaster)",
    "11 Gold Dust Woman (2004 Remaster)",
    "",
    "Music Recorder\\music\\Foreigner IV",
    " <<artiste>>:Foreigner",
    "",
    "01 Night Life",
    "01 No Time To Die",
    "02 Juke Box Hero",
    "03 Break It Up",
    "04 Waiting for a Girl like You",
    "05 Luanne",
    "06 Urgent",
    "07 Im Gonna Win",
    "08 Woman in Black",
    "09 Girl on the Moon",
    "10 Dont Let Go",
    "",
    "Music Recorder\\music\\Gainsbourg Casino de Paris",
    " <<artiste>>:Serge Gainsbourg",
    "",
    "01 Love On The Beat (Live, Casino de Paris _ 1985)",
    "02 Initials B.B. (Live, Casino de Paris _ 1985)",
    "03 Harley Davidson (Live, Casino de Paris _ 1985)",
    "04 Sorry Angel (Live, Casino de Paris _ 1985)",
    "05 Aux armes et c tera (Live, Casino de Paris _ 1985)",
    "06 Nazi Rock (Live, Casino de Paris _ 1985)",
    "07 Des laids des laids (Live, Casino de Paris _ 1985)",
    "08 Ballade de Johnny-Jane (Live, Casino de Paris _ 1985)",
    "09 Bonnie And Clyde (Live, Casino de Paris _ 1985)",
    "10 Vieille canaille (Live, Casino de Paris _ 1985)",
    "11 Im The Boy (Live, Casino de Paris _ 1985)",
    "12 Docteur Jekyll et monsieur Hyde (Live, Casino de Paris _ 1985)",
    "13 Lemon Incest (Extrait) (Live, Casino de Paris _ 1985)",
    "14 Mickey Maousse (Live, Casino de Paris _ 1985)",
    "15 La nostalgie camarade (Live, Casino de Paris _ 1985)",
    "16 Kiss Me Hardy (Live, Casino de Paris _ 1985)",
    "17 D pression au-dessus du jardin (Live, Casino de Paris _ 1985)",
    "18 My Lady Heroine (Live, Casino de Paris _ 1985)",
    "19 Histoires (Live, Casino de Paris _ 1985)",
    "20 Je suis venu te dire que je men vais (Live, Casino de Paris _ 1985)",
    "21 Leau   la bouche (Live, Casino de Paris _ 1985)",
    "22 Lola rastaquou re (Live, Casino de Paris _ 1985)",
    "23 Pr sentation musiciens (Live, Casino de Paris _ 1985)",
    "24 Marilou sous la neige (Live, Casino de Paris _ 1985)",
    "25 No Comment (Live, Casino de Paris _ 1985)",
    "26 Hmm hmm hmm (Live, Casino de Paris _ 1985)",
    "27 Harley David Son Of A Bitch (Live, Casino de Paris _ 1985)",
    "28 La javanaise (Live, Casino de Paris _ 1985)",
    "29 Love On The Beat (Live, Casino de Paris _ 1985 - Rappel)",
    "",
    "Music Recorder\\music\\Here It Is A Tribute to Leonard Cohen",
    " <<artiste>>:Divers_artistes",
    "",
    "01 Steer Your Way",
    "02 Here It Is",
    "03 Suzanne",
    "04 Hallelujah",
    "05 Avalanche",
    "06 Hey, Thats No Way To Say Goodbye",
    "07 Coming Back To You",
    "08 You Want It Darker",
    "09 If It Be Your Will [feat. Mavis Staples]",
    "10 Seems So Long Ago, Nancy",
    "11 Famous Blue Raincoat",
    "12 Bird On The Wire",
    "",
    "Music Recorder\\music\\JJ Goldman Entre gris clair et gris fonc ",
    " <<artiste>>:JJ Goldman",
    "",
    "01 A Quoi Tu Sers (Intro - Album Version)",
    "02 Il changeait la vie",
    "03 Tout petit monde",
    "04 Entre gris clair et gris fonc ",
    "05 L -bas",
    "06 Cest ta chance",
    "07 Des bouts de moi",
    "08 Fais des b b s",
    "09 Puisque tu pars",
    "10 Filles faciles",
    "11 Je commence demain",
    "12 Elle a fait un b b  toute seule",
    "13 Quelque part, quelquun",
    "14 Quelle soit elle",
    "15 Doux",
    "16 Reprendre cest voler",
    "17 Il y a",
    "18 Peur de rien blues",
    "19 Il me restera",
    "20 Appartenir",
    "",
    "Music Recorder\\music\\John Mayer live at the Nokia Theatre",
    " <<artiste>>:John Mayer",
    "",
    "01 Waiting On the World to Change (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "02 Stop This Train (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "03 In Your Atmosphere (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "04 Daughters (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "05 Free Fallin (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "06 Everyday I Have The Blues (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "07 Wait Until Tomorrow (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "08 Who Did You Think I Was (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "09 Come When I Call (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "10 Good Love Is On the Way (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "11 Out of My Mind (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "12 Vultures (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "13 Bold as Love (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "15 Slow Dancing in a Burning Room (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "16 Why Georgia (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "17 The Heart of Life (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "18 I Dont Need No Doctor (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "19 Gravity (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "20 I Dont Trust Myself (With Loving You) (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "21 Belief (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "22 Im Gonna Find Another You (Live at the Nokia Theatre, Los Angeles, CA - December 2007)",
    "",
    "Music Recorder\\music\\Led Zppelin IV",
    " <<artiste>>:Led Zep",
    "",
    "01 Black Dog (Remaster)",
    "02 Rock and Roll (Remaster)",
    "03 The Battle of Evermore (Remaster)",
    "04 Stairway to Heaven (Remaster)",
    "05 Misty Mountain Hop (Remaster)",
    "06 Four Sticks (Remaster)",
    "07 Going to California (Remaster)",
    "08 When the Levee Breaks (Remaster)",
    "09 Black Dog (Basic Track with Guitar Overdubs)",
    "10 Rock and Roll (Alternate Mix)",
    "11 The Battle of Evermore (Mandolin _ Guitar Mix from Headley Grange)",
    "12 Stairway to Heaven (Sunset Sound Mix)",
    "13 Misty Mountain Hop (Alternate Mix)",
    "14 Four Sticks (Alternate Mix)",
    "15 Going to California (Mandolin _ Guitar Mix)",
    "16 When the Levee Breaks (Alternate UK Mix in Progress)",
    "",
    "Music Recorder\\music\\Legende Best Of Johnny",
    " <<artiste>>:Johnny",
    "",
    "01 Le p nitencier",
    "02 Noir cest noir",
    "03 Que je taime",
    "04 Oh ! ma jolie Sarah",
    "05 La musique que jaime",
    "06 Requiem pour un fou",
    "07 Gabrielle",
    "08 Jai oubli  de vivre",
    "09 Quelque chose de Tennessee",
    "10 Lenvie",
    "11 Je te promets",
    "12 Laura",
    "13 Allumer le feu",
    "14 Sang pour sang",
    "15 Marie",
    "16 Diego, libre dans sa t te",
    "",
    "Music Recorder\\music\\Les classiques Rock Fran ais",
    " <<artiste>>:Divers_artistes",
    "",
    "A Tout Moment La Rue",
    "Adr naline",
    "Argent trop cher (Remasteris  En 2006)",
    "Barb s",
    "Butterfly",
    "Contraddiction",
    "Cours vite",
    "Dans mon a roplane blind ",
    "Dis-moi",
    "Domino",
    "Eclair  clair",
    "House On The Moon",
    "Jai vu",
    "Je nveux pas rester sage",
    "Lapologie",
    "Laventurier",
    "Lhomme Press ",
    "Loeuf",
    "La brune",
    "La peau",
    "La sentinelle",
    "La vie est belle",
    "Long Distance Call",
    "Lorelei s basto cha",
    "Marche ou cr ve",
    "Matchistador",
    "Montecristo",
    "New Day",
    "Pas assez de toi",
    "People In The Shadow",
    "Respire",
    "Song For Jedi (Album Version)",
    "Sur la planche 2013",
    "Tant dann es",
    "",
    "Music Recorder\\music\\Les plus grandes voix de la pop",
    " <<artiste>>:Divers_artistes",
    "",
    "Always Remember Us This Way",
    "Billie Jean",
    "Bleeding Love",
    "Bohemian Rhapsody (Remastered 2011)",
    "Chandelier",
    "Dangerous Woman",
    "Dont Start Now",
    "Fallin",
    "For Now",
    "Goodbye Yellow Brick Road (Remastered 2014)",
    "Grace Kelly",
    "Halo",
    "Hero",
    "I Will Always Love You (Ultimate Collection Edit)",
    "Kings & Queens",
    "La Isla Bonita",
    "Mr. Know It All",
    "No Ordinary Love",
    "Pour que tu maimes encore",
    "Rehab",
    "Respect",
    "S&M",
    "Shes No Better Than Me",
    "Someone Like You",
    "Too Good At Goodbyes",
    "Total Eclipse Of The Heart (Re-Recorded)",
    "Upside Down (Original CHIC Mix)",
    "Whats Good",
    "Whats Love Got to Do with It (Symphonic Version)",
    "You Need To Calm Down",
    "",
    "Music Recorder\\music\\Metallica Black Album",
    " <<artiste>>:Metallica",
    "",
    "01 Enter Sandman",
    "02 Sad But True",
    "03 Holier Than Thou",
    "04 The Unforgiven",
    "05 Wherever I May Roam",
    "06 Dont Tread On Me",
    "07 Through The Never",
    "08 Nothing Else Matters",
    "09 Of Wolf And Man",
    "10 The God That Failed",
    "11 My Friend Of Misery",
    "12 The Struggle Within",
    "",
    "Music Recorder\\music\\Mickael Jackson Thriller",
    " <<artiste>>:Mickael Jackson",
    "",
    "01 Wanna Be Startin Somethin",
    "02 Baby Be Mine",
    "03 The Girl Is Mine",
    "04 Thriller",
    "05 Beat It",
    "06 Billie Jean",
    "07 Human Nature",
    "08 P.Y.T. (Pretty Young Thing)",
    "09 The Lady in My Life",
    "",
    "Music Recorder\\music\\Nirvana Never mind",
    " <<artiste>>:Nirvana",
    "",
    "01 Smells Like Teen Spirit",
    "02 In Bloom",
    "03 Come As You Are",
    "04 Breed",
    "05 Lithium",
    "06 Polly",
    "07 Territorial Pissings",
    "08 Drain You",
    "09 Lounge Act",
    "10 Stay Away",
    "11 On A Plain",
    "12 Something In The Way",
    "13 Endless, Nameless",
    "",
    "Music Recorder\\music\\Nirvana unplugged",
    " <<artiste>>:Nirvana",
    "",
    "01 About A Girl (Live)",
    "02 Come As You Are (Live)",
    "03 Jesus Doesnt Want Me For A Sunbeam (Live)",
    "04 The Man Who Sold The World (Live)",
    "05 Pennyroyal Tea (Live)",
    "06 Dumb (Live)",
    "07 Polly (Live)",
    "08 On A Plain (Live)",
    "09 Something In The Way (Live)",
    "10 Plateau (Live)",
    "11 Oh Me (Live)",
    "12 Lake Of Fire (Live)",
    "13 All Apologies (Live)",
    "14 Where Did You Sleep Last Night (Live)",
    "",
    "Music Recorder\\music\\Nirvana unplugged\\Noir Desir 666",
    " <<artiste>>:Noir Desir",
    "",
    "01 666.667 Club",
    "02 Fin de si cle",
    "03 Un jour en France",
    "04   ton  toile",
    "05 Ernestine",
    "06 Comme elle vient",
    "07 Prayer For A Wanker",
    "08 Les persiennes",
    "09 Lhomme press ",
    "",
    "Music Recorder\\music\\Noir Desir 666",
    " <<artiste>>:Noir Desir",
    "",
    "01 666.667 Club",
    "02 Fin de si cle",
    "03 Un jour en France",
    "04   ton  toile",
    "05 Ernestine",
    "06 Comme elle vient",
    "07 Prayer For A Wanker",
    "08 Les persiennes",
    "09 Lhomme press ",
    "10 Lazy",
    "11   la longue",
    "12 Septembre en attendant",
    "13 Song For JLP",
    "",
    "Music Recorder\\music\\Noir Desir Concert",
    " <<artiste>>:Noir Desir",
    "",
    "01 Si rien ne bouge (Live _ 2002)",
    "02 Septembre en attendant (Live _ 2002)",
    "03 One Trip One Noise (Live _ 2002)",
    "04   lenvers   lendroit (Live _ 2002)",
    "05 Les  corch s (Live _ 2002)",
    "06 Le grand incendie (Live _ 2002)",
    "07 Le fleuve (Live _ 2002)",
    "08 La chaleur (Live _ 2002)",
    "09 Des armes (Live _ 2002)",
    "10 Ernestine (Live _ 2002)",
    "11 Tostaky (Live _ 2002)",
    "12 Lazy (Live _ 2002)",
    "13 Pyromane (Live _ 2002)",
    "14   larri re des taxis (Live _ 2002)",
    "15 Lolita nie en bloc (Live _ 2002)",
    "16 Lhomme press  (Live _ 2002)",
    "17 Des visages des figures (Live _ 2002)",
    "18 Bouquet de nerfs (Live _ 2002)",
    "19 Le vent nous portera (Live _ 2002)",
    "20 21st Century Schizo d Man (Live _ 2002)",
    "21 Ces gens-l  (Live _ 2002)",
    "22 Comme elle vient (Live _ 2002)",
    "23   ton  toile (Live _ 2002)",
    "24 Ce nest pas moi qui clame (Live _ 2002)",
    "",
    "Music Recorder\\music\\Pink Floyd Animals",
    " <<artiste>>:Pink Floyd",
    "",
    "01 Pigs On The Wing 1 (2018 Remix)",
    "02 Dogs (2018 Remix)",
    "03 Pigs (Three Different Ones) [2018 Remix]",
    "04 Sheep (2018 Remix)",
    "05 Pigs On The Wing 2 (2018 Remix)",
    "",
    "Music Recorder\\music\\Pink Floyd Pulse",
    " <<artiste>>:Pink Floyd",
    "",
    "01 Shine On You Crazy Diamond (Pts. 1-5, 7) [Live] [2018 Remaster]",
    "02 Astronomy Domine (Live) [2018 Remaster]",
    "03 What Do You Want From Me (Live) [2018 Remaster]",
    "04 Learning To Fly (Live) [2018 Remaster]",
    "05 Keep Talking (Live) [2018 Remaster]",
    "06 Coming Back To Life (Live) [2018 Remaster]",
    "07 Hey You (Live) [2018 Remaster]",
    "08 A Great Day For Freedom (Live) [2018 Remaster]",
    "09 Sorrow (Live) [2018 Remaster]",
    "10 High Hopes (Live) [2018 Remaster]",
    "11 Another Brick In The Wall (Pt. 2) [Live] [2018 Remaster]",
    "12 One Of These Days (Live) [2018 Remaster]",
    "13 Speak To Me (Live) [2018 Remaster]",
    "14 Breathe (Live) [2018 Remaster]",
    "15 On The Run (Live) [2018 Remaster]",
    "16 Time (Live) [2018 Remaster]",
    "17 The Great Gig In The Sky (Live) [2018 Remaster]",
    "18 Money (Live) [2018 Remaster]",
    "19 Us And Them (Live) [2018 Remaster]",
    "20 Any Colour You Like (Live) [2018 Remaster]",
    "21 Brain Damage (Live) [2018 Remaster]",
    "22 Eclipse (Live) [2018 Remaster]",
    "23 Wish You Were Here (Live) [2018 Remaster]",
    "24 Comfortably Numb (Live) [2018 Remaster]",
    "25 Run Like Hell (Live) [2018 Remaster]",
    "",
    "Music Recorder\\music\\Pink Floyd The Dark Side of The Moon",
    " <<artiste>>:Pink Floyd",
    "",
    "01 Speak To Me (2023 Remaster)",
    "02 Breathe (In The Air) [2023 Remaster]",
    "03 On The Run (2023 Remaster)",
    "04 Time (2023 Remaster)",
    "05 The Great Gig In The Sky (2023 Remaster)",
    "06 Money (2023 Remaster)",
    "07 Us And Them (2023 Remaster)",
    "08 Any Colour You Like (2023 Remaster)",
    "09 Brain Damage (2023 Remaster)",
    "10 Eclipse (2023 Remaster)",
    "",
    "Music Recorder\\music\\Plaisir coupable",
    " <<artiste>>:Divers_artistes",
    "",
    "99 Luftballons (2009)",
    "Africa",
    "Barbie Girl",
    "Besoin de rien, envie de toi",
    "Boule de flipper",
    "Boys (Summertime Love)",
    "Ca Plane Pour Moi",
    "Confidence pour confidence (Version originale 1981)",
    "Cruel Summer",
    "Dont Stop Believin",
    "Dragostea Din Tei (Romanian Version)",
    "Du Rhum Des Femmes",
    "Elle a les yeux revolver",
    "Femme que jaime",
    "Flash",
    "Freed from Desire",
    "Girls Just Want to Have Fun",
    "Jirai o  tu iras",
    "Joue pas",
    "Laventurier",
    "La goffa Lolita",
    "La tribu de Dana",
    "Le Banana Split (Radio Mix)",
    "Le coup de folie",
    "Le jerk",
    "Les lacs du Connemara",
    "Les sunlights des tropiques",
    "Macumba (Version longue)",
    "Mald n (Version originale)",
    "Mambo No. 5 (a Little Bit of...)",
    "Never Gonna Give You Up (2022 - Remaster)",
    "Partenaire Particulier",
    "Pour que tu maimes encore",
    "Sweet Dreams (Are Made of This) (Remastered)",
    "Ten va pas",
    "Toute premi re fois (Version longue)",
    "Voyage, voyage",
    "Wake Me Up Before You Go-Go",
    "Wannabe",
    "When the Rain Begins to Fall",
    "Youre My Heart, Youre My Soul 98 (Remastered)",
    "_Baby One More Time",
    "",
    "Music Recorder\\music\\Queen At Night At the Opera",
    " <<artiste>>:Queen",
    "",
    "01 Death On Two Legs (Dedicated To...)",
    "02 Lazing On A Sunday Afternoon (Remastered 2011)",
    "03 Im In Love With My Car (Remastered 2011)",
    "04 Youre My Best Friend (Remastered 2011)",
    "05 39 (Remastered 2011)",
    "06 Sweet Lady (Remastered 2011)",
    "07 Seaside Rendezvous (Remastered 2011)",
    "08 The Prophets Song (Remastered 2011)",
    "09 Love Of My Life (Remastered 2011)",
    "10 Good Company (Remastered 2011)",
    "11 Bohemian Rhapsody (Remastered 2011)",
    "12 God Save The Queen (Remastered 2011)",
    "",
    "Music Recorder\\music\\Rage against the machine",
    " <<artiste>>:Rage against the machine",
    "",
    "01 Bombtrack",
    "02 Killing In The Name",
    "03 Take The Power Back",
    "04 Settle For Nothing",
    "05 Bullet In The Head",
    "06 Know Your Enemy",
    "07 Wake Up",
    "08 Fistful Of Steel",
    "09 Township Rebellion",
    "10 Freedom",
    "",
    "Music Recorder\\music\\Rediscover Alain Bashung",
    " <<artiste>>:Alain Bashung",
    "",
    "Gaby oh Gaby (Remix 1991)",
    "Immortels",
    "La nuit je mens",
    "Ma petite entreprise",
    "Osez Jos phine",
    "Osez Jos phine_1",
    "R sidents de la R publique",
    "Tant de nuits",
    "Vertige de lamour",
    "",
    "Music Recorder\\music\\REDISCOVER Billie Eilish",
    " <<artiste>>:Billie Eilish",
    "",
    "&burn",
    "all the good girls go to hell",
    "bad guy",
    "bellyache",
    "bitches broken hearts",
    "Bored",
    "bury a friend",
    "come out and play",
    "COPYCAT",
    "everything i wanted (Prime Day Show x Billie Eilish)",
    "everything i wanted",
    "Getting Older",
    "Happier Than Ever",
    "I Didnt Change My Number",
    "i love you",
    "idontwannabeyouanymore",
    "Lo Vas A Olvidar",
    "Lost Cause",
    "lovely",
    "my boy",
    "my future",
    "my strange addiction",
    "NDA",
    "No Time To Die",
    "ocean eyes",
    "Oxytocin",
    "party favor",
    "Six Feet Under",
    "The 30th",
    "Therefore I Am (Prime Day Show x Billie Eilish)",
    "Therefore I Am",
    "TV",
    "watch",
    "What Was I Made For_ [From The Motion Picture _Barbie_]",
    "WHEN I WAS OLDER (Music Inspired By The Film ROMA)",
    "when the partys over",
    "wish you were gay",
    "you should see me in a crown",
    "Your Power (Prime Day Show x Billie Eilish)",
    "Your Power",
    "",
    "Music Recorder\\music\\REDISCOVER Bob Marley",
    " <<artiste>>:Bob Marley",
    "",
    "400 Years",
    "Africa Unite",
    "Buffalo Soldier",
    "Burnin And Lootin",
    "Coming In From The Cold",
    "Concrete Jungle",
    "Could You Be Loved",
    "Crazy Baldhead",
    "Duppy Conqueror",
    "Easy Skanking",
    "Exodus",
    "Forever Loving Jah",
    "Get Up, Stand Up",
    "Give Thanks &  Praises",
    "I Shot The Sheriff",
    "Is This Love",
    "Judge Not",
    "Kaya",
    "Kinky Reggae",
    "Lively Up Yourself",
    "Natty Dread",
    "No More Trouble",
    "One Drop",
    "One Love _ People Get Ready",
    "Pimpers Paradise",
    "Positive Vibration",
    "Punky Reggae Party (Live At The Pavillon De Paris, 1977)",
    "Rat Race (Live At The Pavillon De Paris, 1977)",
    "Rebel Music (3 OClock Roadblock) (Live At The Lyceum, London_July 17,1975)",
    "Redemption Song",
    "Roots, Rock, Reggae",
    "Satisfy My Soul",
    "Simmer Down",
    "Small Axe",
    "So Much Trouble In The World",
    "Soul Rebel",
    "Soul Shakedown Party",
    "Stir It Up",
    "Sun Is Shining",
    "Talkin Blues (Alternate Version)",
    "Them Belly Full (But We Hungry)",
    "Time Will Tell",
    "Trenchtown Rock (Live At The Lyceum, London_1975)",
    "Waiting In Vain",
    "",
    "Music Recorder\\music\\REDISCOVER Laurent Voulzy",
    " <<artiste>>:Laurent Voulzy",
    "",
    "All I Have to Do Is Dream",
    "Belem (Live)",
    "Belle- le-en-Mer, Marie-Galante",
    "Bubble Star, Pt. 1",
    "Cocktail chez mademoiselle",
    "Derniers baisers",
    "D sir, d sir, Pt. 1",
    "Grimaud",
    "Je suis venu pour elle",
    "Jeanne",
    "Karin Redinger",
    "La fille davril",
    "Le coeur grenadine",
    "Le pouvoir des fleurs",
    "Le r ve du pecheur",
    "Le soleil donne",
    "Les nuits sans Kim Wilde",
    "Loreley, Loreley (Radio Edit)",
    "My Song Of You",
    "Paradoxal syst me",
    "Quand le soleil se couche",
    "Rockollection",
    "",
    "Music Recorder\\music\\REDISCOVER Santana",
    " <<artiste>>:Carlos Santana",
    "",
    "(Da Le) Yaleo",
    "Africa Bamba",
    "Black Magic Woman _ Gypsy Queen",
    "Corazon Espinado",
    "El Farol",
    "Europa (Earths Cry Heavens Smile)",
    "Everybodys Everything",
    "Evil Ways",
    "Greener",
    "Hold On",
    "Interplanetary Party",
    "Into the Night",
    "Jingo (Single Version)",
    "Joy",
    "Just Feel Better",
    "La Flaca feat. Juanes",
    "Maria Maria",
    "Migra",
    "Move",
    "No One to Depend On",
    "Oye Como Va",
    "Oye Este Mi Canto [feat. Buika]",
    "Put Your Lights On",
    "Samba Pa Ti",
    "Say It Again",
    "Singing Winds, Crying Beasts",
    "Smooth",
    "Soul Sacrifice",
    "The Game of Love (Main _ Radio Mix)",
    "While My Guitar Gently Weeps",
    "Winning",
    "",
    "Music Recorder\\music\\REDISCOVER Serge Gainsbourg",
    " <<artiste>>:Serge Gainsbourg",
    "",
    "69 ann e  rotique [feat. Jane Birkin]",
    "Aux armes et caetera",
    "Bonnie And Clyde",
    "Chanson de Maglia",
    "Comic Strip",
    "Comme un boomerang",
    "Couleur Caf ",
    "Dieu fumeur de havanes (Bande originale du film _Je vous aime_)",
    "Elaeudanla t it ia",
    "Elisa (Bande originale du film _Lhorizon_)",
    "Goodbye Emmanuelle (Bande originale du film _Goodbye Emmanuelle_)",
    "Hmm Hmm Hmm",
    "Initials B.B_",
    "Je suis venu te dire que je men vais",
    "Je taime moi non plus [feat. Serge Gainsbourg]",
    "Je taime moi non plus",
    "Kate",
    "La chanson de Pr vert",
    "La Javanaise",
    "La Saison des pluies",
    "Le poin onneur des Lilas",
    "Lemon Incest (Dapr s l tude Opus 10 N 3 En Mi Majeur de Chopin) [feat. Charlotte Gainsbourg]",
    "Lola rastaquou re",
    "Love On The Beat",
    "Mon l gionnaire",
    "Nazi Rock",
    "Qui est In_, qui est _Out_",
    "Requiem pour un c... (Bande originale du film _Le pacha_)",
    "Sea, Sex And Sun",
    "Sois belle et tais-toi",
    "Vieille canaille",
    "Youre Under Arrest",
    "",
    "Music Recorder\\music\\REDISCOVER Stevie Ray Vaughan",
    " <<artiste>>:SRV",
    "",
    "Blues At Sunrise",
    "Boot Hill",
    "Change It",
    "Close To You",
    "Cold Shot",
    "Come On (Pt. III)",
    "Couldnt Stand The Weather",
    "Crossfire",
    "Dirty Pool",
    "Empty Arms",
    "Give Me Back My Wig",
    "Hide Away",
    "Honey Bee",
    "Im Cryin",
    "Leave My Girl Alone",
    "Lenny",
    "Let Me Love You Baby",
    "Life by the Drop",
    "Life Without You",
    "Little Wing",
    "Long Way from Home",
    "Look At Little Sister",
    "Love Me Darlin",
    "Love Struck Baby",
    "Mary Had a Little Lamb",
    "Match Box Blues",
    "May I Have A Talk With You",
    "Pride and Joy",
    "Rude Mood",
    "Say What!",
    "Scratch-N-Sniff",
    "Scuttle Buttin",
    "Shake for Me (Live at Steamboat 1874, Austin, TX - April 1980)",
    "So Excited",
    "Telephone Song",
    "Tell Me",
    "Testify",
    "Texas Flood",
    "The House Is Rockin",
    "The Sky Is Crying",
    "The Things (That) I Used To Do",
    "Tightrope",
    "Tin Pan Alley (AKA Roughest Place in Town) (1982 Version)",
    "Voodoo Child (Slight Return)",
    "Wall of Denial",
    "",
    "Music Recorder\\music\\REDISCOVER The 80s",
    " <<artiste>>:Divers_artistes",
    "",
    "99 Luftballons",
    "Africa",
    "Another One Bites The Dust (Remastered 2011)",
    "Back In Black",
    "Billie Jean",
    "Born in the U.S.A_",
    "Born to Be Alive (Extended Version)",
    "Could You Be Loved",
    "Dont Stop Believin",
    "D s que le vent soufflera",
    "Easy Lover",
    "Elle est dailleurs",
    "Encore et encore (Remastered)",
    "Eve l ve-toi",
    "Every Breath You Take",
    "Eye of the Tiger",
    "Girls Just Want to Have Fun",
    "Goodbye Marylou",
    "Im Still Standing",
    "Il jouait du piano debout (Remasteris  en 2004)",
    "In the Air Tonight (2015 Remaster)",
    "Je te promets",
    "Jump (2015 Remaster)",
    "Laventurier",
    "LAziza",
    "La groupie du pianiste (Remasteris  en 2002)",
    "Les sunlights des tropiques",
    "Lets Dance (2018 Remaster)",
    "Livin On A Prayer",
    "Maneater",
    "Material Girl (7_ Version) [2022 Remaster]",
    "Nuit de folie",
    "Partenaire Particulier",
    "Purple Rain (2015 Paisley Park Remaster)",
    "Quand la musique est bonne",
    "Running Up That Hill (A Deal With God) [2018 Remaster]",
    "Sans contrefa on (Mix 2001)",
    "Sar  perch  ti amo",
    "Should I Stay or Should I Go (Remastered)",
    "Still Loving You",
    "Sweet Child O Mine",
    "Sweet Dreams (Are Made of This) [2018 Remastered]",
    "Tainted Love",
    "Take on Me",
    "The Final Countdown",
    "Un autre monde (Remasteris  en 2015)",
    "Voyage, voyage",
    "Wake Me Up Before You Go-Go",
    "Wicked Game",
    "With Or Without You",
    "",
    "Music Recorder\\music\\REDISCOVER The 80s_ Vari t  Fra",
    " <<artiste>>:Divers_artistes",
    "",
    "Je te donne.mp3",
    "Je te promets.mp3",
    "Laventurier.mp3",
    "LAziza.mp3",
    "Lenvie.mp3",
    "Mistral gagnant.mp3",
    "Tous les cris les S.O.S_.mp3",
    "",
    "Music Recorder\\music\\REM Out of Time",
    " <<artiste>>:REM",
    "",
    "01 Radio Song",
    "02 Losing My Religion",
    "03 Low",
    "04 Near Wild Heaven",
    "05 Endgame",
    "06 Shiny Happy People",
    "07 Belong",
    "08 Half A World Away",
    "09 Texarkana",
    "10 Country Feedback",
    "11 Me In Honey",
    "12 Losing My Religion 1 (Demo)",
    "13 Near Wild Heaven 1 (Demo)",
    "14 Shiny Happy People 1 (Demo)",
    "15 Texarkana 1 (Demo)",
    "16 Untitled Demo 2",
    "17 Radio - Acoustic (Radio Song 1) (Demo)",
    "18 Near Wild Heaven 2 (Demo)",
    "19 Shiny Happy People 2 (Demo)",
    "20 Slow Sad Rocker (Endgame) (Demo)",
    "21 Radio - Band (Radio Song 3) (Demo)",
    "22 Losing My Religion 2 (Demo)",
    "23 Belong (Demo)",
    "24 Blackbirds (Half A World Away) (Demo)",
    "25 Texarkana (Demo)",
    "26 Country Feedback (Demo)",
    "27 Me On Keyboard (Me In Honey) (Demo)",
    "28 Low (Demo)",
    "29 40 Sec. (40 Second Song) (Demo)",
    "30 Fretless 1 (Demo)",
    "",
    "Music Recorder\\music\\Renaud compilation",
    " <<artiste>>:Renaud",
    "",
    "01 Morgane de toi",
    "02 Marche   lombre",
    "03 Dans mon H.L.M_",
    "04 Hexagone",
    "05 Ou cest qujai mis mon flingue _",
    "06 Lauto-stoppeuse",
    "07 La bande   Lucien",
    "08 Salut manouche",
    "09 Sans dec",
    "10 Adieu minette",
    "11 Le gringalet",
    "12 Doudou sen fout",
    "13 Jai rat  T l -Foot",
    "14 La blanche",
    "15 Amoureux de Paname",
    "16 Pr s des autos tamponneuses",
    "17 Je suis une bande de jeunes",
    "18 Deuxi me g n ration",
    "19 Laisse b ton",
    "20 Manu",
    "21 Ma gonzesse",
    "22 Mon beauf",
    "23 Les aventures de G rard Lambert",
    "24 Les charognards",
    "25 La teigne",
    "26 La tire   D d ",
    "27 D serteur",
    "28 Pochtron",
    "29 Le P re No l noir",
    "30 Chtimi rock",
    "31 Germaine",
    "32 Jojo le d mago",
    "33 La menthe   leau",
    "34 Le retour de G rard Lambert",
    "35 D s que le vent soufflera",
    "36 En cloque",
    "37 It Is Not Because You Are",
    "38 Chanson pour Pierrot",
    "39 Oscar",
    "40 Jai la vie qui mpique les yeux",
    "41 Ptit dej blues",
    "42 Soci t  tu mauras pas",
    "43 Cest mon dernier bal",
    "44 Le blues de la Porte dOrl ans",
    "45 Le tango de Massy-Palaiseau",
    "46 Ma chanson leur a pas plu",
    "47 Banlieue rouge",
    "48 Etudiant poil aux dents",
    "49 Gueule daminche",
    "",
    "Music Recorder\\music\\Rita Mitsouko",
    " <<artiste>>:Rita Mitsouko",
    "",
    "01 Marcia Ba la",
    "02 Andy",
    "03 Jalousie",
    "04 Hip Kit",
    "05 Dont Forget the Nite",
    "06 Cest comme  a",
    "07 Singing in the Shower",
    "08 Les histoires da",
    "09 Le petit train",
    "",
    "Music Recorder\\music\\Sade Best Of",
    " <<artiste>>:Sade",
    "",
    "01 Your Love Is King",
    "02 Hang on to Your Love",
    "03 Smooth Operator (Single Version)",
    "04 Jezebel",
    "05 The Sweetest Taboo",
    "06 Is It a Crime",
    "07 Never as Good as the First Time",
    "08 Love Is Stronger Than Pride",
    "09 Paradise",
    "10 Nothing Can Come Between Us",
    "11 No Ordinary Love",
    "12 Like a Tattoo",
    "13 Kiss of Life",
    "14 Please Send Me Someone to Love",
    "15 Cherish the Day",
    "16 Pearls",
    "",
    "Music Recorder\\music\\Sardou concert",
    " <<artiste>>:Michel Sardou",
    "",
    "01 Salut (Live   La Seine Musicale _ 2018)",
    "02 La java de Broadway (Live   La Seine Musicale _ 2018)",
    "03 Vladimir Ilitch (Live   La Seine Musicale _ 2018)",
    "04 Je vais taimer (Live   La Seine Musicale _ 2018)",
    "05 San Lorenzo (Live   La Seine Musicale _ 2018)",
    "06 Laigle noir (Live   La Seine Musicale _ 2018)",
    "07 Le bac G (Live   La Seine Musicale _ 2018)",
    "08 Le France (Live   La Seine Musicale _ 2018)",
    "09 Medley _ En chantant _ Les bals populaires _ Le rire du sergent (Live   La Seine Musicale _ 2018)",
    "10 La maladie damour (Live   La Seine Musicale _ 2018)",
    "11 Lan mil (Live   La Seine Musicale _ 2018)",
    "12 Une fille aux yeux clairs (Live   La Seine Musicale _ 2018)",
    "13 Les ricains (Live   La Seine Musicale _ 2018)",
    "14  tre une femme (Live   La Seine Musicale _ 2018)",
    "15 Le figurant (Live   La Seine Musicale _ 2018)",
    "16 Il  tait l  (le fauteuil) (Live   La Seine Musicale _ 2018)",
    "17 Io Domenico (Live   La Seine Musicale _ 2018)",
    "18 Je vole (Live   La Seine Musicale _ 2018)",
    "19 Comme dhabitude (Live   La Seine Musicale _ 2018)",
    "20 Afrique adieu (Live   La Seine Musicale _ 2018)",
    "21 Musulmanes (Live   La Seine Musicale _ 2018)",
    "22 La derni re danse (Live   La Seine Musicale _ 2018)",
    "23 Les lacs du Connemara (Live   La Seine Musicale _ 2018)",
    "",
    "Music Recorder\\music\\slow ann e 80",
    " <<artiste>>:Divers_artistes",
    "",
    "(Everything I Do) I Do It For You",
    "Body Talk",
    "Bohemian Rhapsody",
    "Candle In The Wind 1997",
    "Carrie",
    "Classic",
    "Come with Me (2016 Remaster)",
    "Easy",
    "Every Breath You Take",
    "Everybodys Got to Learn Sometime",
    "Exhale (Shoop Shoop) (from _Waiting to Exhale_ - Original Soundtrack)",
    "Hello",
    "Hopelessly Devoted To You (From _Grease_ Original Motion Picture Soundtrack).mp3",
    "Hunting High and Low",
    "I Just Cant Stop Loving You (2012 Remaster)",
    "In the Heat of the Night",
    "Les corons",
    "Make It Last Forever (with Jacci McGhee)",
    "Margherita",
    "November Rain",
    "One More Try (Remastered)",
    "Ordinary World",
    "Overjoyed",
    "Precious Thing",
    "Ready to Follow You",
    "Reality",
    "Reasons",
    "Right Here Waiting",
    "Rock Me Tonight (For Old Times Sake).mp3",
    "Saving All My Love for You",
    "Say You, Say Me",
    "Sexual Healing",
    "Shes Like the Wind (From _Dirty Dancing_ Soundtrack)",
    "Still Got the Blues",
    "Still Loving You",
    "Stop",
    "Suddenly",
    "Superwoman",
    "The Captain of Her Heart",
    "The Lady in Red",
    "Too Hot",
    "True",
    "Un-Break My Heart",
    "Up Where We Belong",
    "Wind Of Change",
    "",
    "Music Recorder\\music\\Souchon Triple Best Of",
    " <<artiste>>:Alain Souchon",
    "",
    "01 Parachute dor ",
    "02 La vie Th odore",
    "03 Bonjour tristesse",
    "04 Lisa",
    "05 L le du d dain",
    "06 Le myst re",
    "07 Et si en plus ya personne",
    "08   cause delle",
    "09 Jaimais mieux quand c tait toi",
    "10 La vie ne vaut rien",
    "11 Caterpillar",
    "12 Putain  a penche",
    "13 Petit tas tomb ",
    "14 C tait menti",
    "15 Au ras des p querettes",
    "16 Lhorrible Bye Bye",
    "17 Sous les jupes des filles",
    "18 Lamour   la machine",
    "19 Rive gauche",
    "20 Le baiser",
    "21 Pardon",
    "22 Bye Bye Lady Dame",
    "23 Tailler la zone",
    "24 Cest d j   a",
    "25 Sans queue ni t te",
    "26 Le fil",
    "27 Chanter cest lancer des balles",
    "28 Arlette Laguiller",
    "29 Les filles  lectriques",
    "30 Foule sentimentale",
    "31 Les regrets",
    "32 La beaut  dAva Gardner",
    "33 Le bateau mouche",
    "34 On se cache des choses",
    "35 Normandie lusitania",
    "36 Quand jserai K.O_",
    "37 Ultra moderne solitude",
    "38 La chanson parfaite",
    "39 Jattends quelquun",
    "40 Dandy",
    "41 Com die",
    "42 Les cadors",
    "43 Vous  tes lents",
    "44 Jveux du cuir",
    "45 La ballade de Jim",
    "46 Pourquoi tu tpr pares",
    "47 Pays industriels",
    "48 Les jours sans moi",
    "49 Cest comme vous voulez",
    "50 La vie intime est maritime",
    "51 Portbail",
    "",
    "Music Recorder\\music\\Starmania",
    " <<artiste>>:Divers_artistes",
    "",
    "01 Ouverture (Live) [Remastered]",
    "02 Il se passe quelque chose   Monopolis (Live) [Remastered]",
    "03 Quand on arrive en ville (Live) [Remastered]",
    "04 Communiqu  de lEvang liste (Live) [2009 Remaster]",
    "05 Travesti (Live) [Remastered]",
    "06 Banlieue nord (Live) [Remastered]",
    "07 Sadia et Johnny (Live) [Remastered]",
    "08 La serveuse et les clients (Live) [Remastered]",
    "09 La complainte de la serveuse automate (Live) [Remastered]",
    "10 Conf rence de presse de Z ro Janvier (Live) [Remastered]",
    "11 Le blues du businessman (Live) [Remastered]",
    "12 Communiqu  de lEvang liste 2 (Live) [Remastered]",
    "13 Starmania (Live) [Remastered]",
    "14 Un gar on pas comme les autres (Live) [Remastered]",
    "15 La chanson de Ziggy (Live) [Remastered]",
    "16 Le coup de t l phone (Live) [Remastered]",
    "17 Interview de Johnny Rockfort (Live) [Remastered]",
    "18 Un enfant de la pollution (Live) [Remastered]",
    "19 Communiqu  de lEvang liste 3 (Live) [Remastered]",
    "20 Le meeting de z ro Janvier (Live) [Remastered]",
    "21 Le bulletin sp cial de T l  Capitale (Live) [Remastered]",
    "22 Besoin damour (Live) [Remastered]",
    "23 La procession du grand Gourou (Live) [Remastered]",
    "24 Communiqu  de lEvang liste 4 (Live) [Remastered]",
    "25 Marie-Jeanne et les clients du caf  (Live) [Remastered]",
    "26 Les adieux dun sex symbol (Remastered)",
    "27 Le t l gramme de z ro   Stella (Live) [Remastered]",
    "28 Communiqu  de lEvang liste et Marie-Jeanne (Live) [Remastered]",
    "29 Trio de la jalousie (Live) [Remastered]",
    "30 S.O.S. dun terrien en d tresse (Live) [Remastered]",
    "31 Jingle de Stella (Live) [Remastered]",
    "32 Le d bat t l vis  (Live) [Remastered]",
    "33 Sex-shops, cin mas pornos (Live) [Remastered]",
    "34 Les parents de Cristal (Live) [Remastered]",
    "35 Quand on na plus rien   perdre (Live) [Remastered]",
    "36 Ladieu de Marie-Jeanne   Ziggy (Live) [Remastered]",
    "37 Les uns contre les autres (Live) [Remastered]",
    "38 La demande de Z ro   Stella (Live) [Remastered]",
    "39 Ego trip (Live) [Remastered]",
    "40 Communiqu  de lEvang liste 5 (Live) [Remastered]",
    "41 Petite musique terrienne (Live) [Remastered]",
    "42 Monopolis (Live) [Remastered]",
    "43 Communiqu  de lEvang liste 6 (Live) [Remastered]",
    "44 Disc-Jockeys Song (Live) [2009 Remastered]",
    "45 Ce soir on danse   Naziland (Live) [Remastered]",
    "46 Le tango de lamour et de la mort (Live) [Remastered]",
    "47 Ce soir on danse   Naziland 2 (Live) [Remastered]",
    "48 Le monde est stone (Live) [Remastered]",
    "49 La victoire de z ro Janvier (Live) [Remastered]",
    "50 Le r ve de Stella (Live) [Remastered]",
    "51 Final (Live) [Remastered]",
    "",
    "Music Recorder\\music\\Sting My Songs",
    " <<artiste>>:Sting",
    "",
    "01 Brand New Day (My Songs Version)",
    "02 Desert Rose (My Songs Version)",
    "03 If You Love Somebody Set Them Free (My Songs Version)",
    "04 Every Breath You Take (My Songs Version)",
    "05 Demolition Man (My Songs Version)",
    "06 Cant Stand Losing You (My Songs Version)",
    "07 Fields Of Gold (My Songs Version)",
    "08 So Lonely (My Songs Version)",
    "09 Shape Of My Heart (My Songs Version)",
    "10 Message In A Bottle (My Songs Version)",
    "11 Fragile (My Songs Version)",
    "12 Walking On The Moon (My Songs Version)",
    "13 Englishman In New York (My Songs Version)",
    "14 If I Ever Lose My Faith In You (My Songs Version)",
    "15 Roxanne (Live)",
    "16 Synchronicity II (Live)",
    "17 Next To You (Live)",
    "18 Spirits In The Material World (Live)",
    "19 Fragile (Live)",
    "",
    "Music Recorder\\music\\Supertramp Breakfast In America",
    " <<artiste>>:Supertramp",
    "",
    "01 Gone Hollywood (2010 Remastered)",
    "02 The Logical Song (Remastered 2010)",
    "03 Goodbye Stranger (2010 Remastered)",
    "04 Breakfast In America (2010 Remastered)",
    "05 Oh Darling (2010 Remastered)",
    "06 Take The Long Way Home (2010 Remastered)",
    "07 Lord Is It Mine (2010 Remastered)",
    "08 Just Another Nervous Wreck (2010 Remastered)",
    "09 Casual Conversations (2010 Remastered)",
    "10 Child Of Vision (2010 Remastered)",
    "",
    "Music Recorder\\music\\Telephone Best Of",
    " <<artiste>>:Telephone",
    "",
    "01 La bombe humaine (Live)",
    "02 Hygiaphone",
    "03 Argent trop cher",
    "04 Crache ton venin",
    "05 Au coeur de la nuit",
    "06 Dure limite",
    "07  a cest vraiment toi",
    "08 Un autre monde",
    "09 Oublie  a",
    "10 New-York avec toi",
    "11 Electric cit ",
    "12 Jour contre jour",
    "13 Le Chat",
    "14 Le Jour sest lev ",
    "15 Cendrillon (Live)",
    "16 Tout  a cest du cinema",
    "",
    "Music Recorder\\music\\Thiefaine 40 ans de chanson",
    " <<artiste>>:HF Thiefaine",
    "",
    "01 Je ten remets au vent (Remastered)",
    "02 La fille du coupeur de joints (Remastered)",
    "03 La d che, le twist et le reste (Remastered)",
    "04 La m me kal  doscope (Remastered)",
    "05 Alligators 427 (Remastered)",
    "06 Groupie 89 turbo 6 (Remastered)",
    "07 113 me cigarette sans dormir (2018 Remastered Version)",
    "08 Narcisse 81 (2018 Remastered Version)",
    "09 Math matiques souterraines (2018 Remastered Version)",
    "10 Soleil cherche futur (2018 Remastered Version)",
    "11 Lorelei s basto cha (2018 Remastered Version)",
    "12 Les dingues et les paum s (2018 Remastered Version)",
    "13 Stalag-tilt (Remastered)",
    "14 Femme de Loth (Remastered)",
    "15 Dies Ol  Sparadrap Joey (Remastered)",
    "16 Bip de   station verticale (Remastered)",
    "17 Sweet amanite phallo de Queen (Remastered)",
    "18 Was ist das, RocknRoll (Remastered)",
    "19 Septembre rose (Remastered)",
    "20 Demain les Kids",
    "21 Un automne   Tanger",
    "22 Cr puscule - transfert",
    "23 Animal en quarantaine",
    "24 Des adieux",
    "25 La ballade dAbdallah Geronimo Cohen",
    "26 Quand la banlieue descendra sur la ville",
    "27 Confessions dun Never Been",
    "28 Le jeu de la folie",
    "29 Avenue de lamour",
    "30 La ruelle des morts",
    "31 Fi vre resurrectionnelle",
    "32 Petit matin 4.10 heure d t ",
    "33 Ang lus",
    "34 Strat gie de linespoir",
    "35 Karaganda (camp 99)",
    "36 Le temps des tachyons",
    "",
    "Music Recorder\\music\\U2 WAR",
    " <<artiste>>:U2",
    "",
    "01 Sunday Bloody Sunday (Remastered 2008)",
    "02 Seconds (Remastered 2008)",
    "03 New Years Day (Remastered 2008)",
    "04 Like A Song... (Remastered 2008)",
    "05 Drowning Man (Remastered 2008)",
    "06 The Refugee (Remastered 2008)",
    "07 Two Hearts Beat As One (Remastered 2008)",
    "08 Red Light (Remastered 2008)",
    "09 Surrender (Remastered 2008)",
    "10 _40_ (Remastered 2008)",
    "11 Endless Deep (Remastered)",
    "12 Angels Too Tied To The Ground",
    "13 New Years Day (Single Edit - Remastered)",
    "14 New Years Day (USA Remix _ Kevorkian Remix _ Remastered)",
    "15 New Years Day (Vocal Extended Mix _ Ferry Corsten Remix)",
    "16 New Years Day (Ferry Corsten  - Vocal Radio mix)",
    "17 Two Hearts Beat As One (Long Mix By Kevorkian _ Remastered)",
    "18 Two Hearts Beat As One (USA Remix by Kevorkian _ Remastered)",
    "19 Two Hearts Beat As One (Club Version - Steve Lillywhite Re-mix - Remastered)",
    "20 Treasure (Whatever Happened To Pete The Chop) (Remastered)",
    "21 I Threw A Brick Through A Window_A Day Without Me (Live from Werchter, Belgium July 1982 - Remastered)",
    "22 Fire (Live from Werchter, Belgium, July 1982 - Remastered)",
    "",
    "Music Recorder\\music\\Van Halen 1984",
    " <<artiste>>:Van Halen",
    "",
    "01 1984 (2015 Remaster)",
    "02 Jump (2015 Remaster)",
    "03 Panama (2015 Remaster)",
    "04 Top Jimmy (2015 Remaster)",
    "05 Drop Dead Legs (2015 Remaster)",
    "06 Hot for Teacher (2015 Remaster)",
    "07 Ill Wait (2015 Remaster)",
    "08 Girl Gone Bad (2015 Remaster)",
    "09 House of Pain (2015 Remaster)",
    "",
    "",
    "Music Recorder\\music\\Ma selection dance",
    " <<artiste>>:Divers_artistes",
    "",
    "",
    "Bakermat - Baby.mp3",
    "Beyonce - Crazy In Love.mp3",
    "Bruno Mars - 24K Magic.mp3",
    "Bruno Mars - Locked Out Of Heaven.mp3",
    "Calvin Harris - Feels.mp3",
    "Daft Punk - Get Lucky (Radio Edit).mp3",
    "DNCE - Kissing Strangers.mp3",
    "Ed Sheeran - Shape of You.mp3",
    "Ester - Dont Be so Shy (Originally Perfomed by Imany).mp3",
    "Gnarls Barkley - Crazy.mp3",
    "Haddaway - What Is Love (Original 7_ Mix).mp3",
    "Helmut Fritz - Ca menerve (Radio Edit).mp3",
    "Lartiste - Chocolat (feat. Awa Imani).mp3",
    "LMFAO - Party Rock Anthem.mp3",
    "Luis Fonsi - Despacito.mp3",
    "Madcon - Beggin.mp3",
    "Maroon 5 - Dont Wanna Know.mp3",
    "Maroon 5 - Moves Like Jagger (Studio Recording From The Voice Performance).mp3",
    "OneRepublic - Counting Stars.mp3",
    "Owl City - Good Time.mp3",
    "Pharrell Williams - Happy (From _Despicable Me 2_).mp3",
    "Psy - Gangnam Style (?????).mp3",
    "Robin Schulz - Sugar (feat. Francesco Yates).mp3",
    "Robin Thicke - Blurred Lines.mp3",
    "Stromae - Alors On Danse (Radio Edit).mp3",
    "The Weeknd - I Feel It Coming.mp3",
    "Train - Drive By.mp3",
    "",
    "Music Recorder\\music\\Ma selection Disco",
    " <<artiste>>:Divers_artistes",
    "",
    "ABBA - Dancing Queen.mp3",
    "ABBA - Gimme! Gimme! Gimme! (A Man After Midnight).mp3",
    "Aqua - Barbie Girl.mp3",
    "Boney M. - Daddy Cool.mp3",
    "Chagrin Damour - Chacun fait (cqui lui plait) (Version originale 1981).mp3",
    "Chic - Good Times.mp3",
    "Chic - Le Freak.mp3",
    "Claude Francois - Alexandrie Alexandra.mp3",
    "Debut de Soiree - Nuit de folie.mp3",
    "Desireless - Voyage voyage.mp3",
    "Earth_ Wind & Fire - Boogie Wonderland.mp3",
    "Earth_ Wind & Fire - September.mp3",
    "Electric Light Orchestra - Last Train to London.mp3",
    "Frankie Goes to Hollywood - Relax.mp3",
    "IAM - Je danse le Mia.mp3",
    "Images - Les demons de minuit.mp3",
    "Indeep - Last Night a DJ Save My Life.mp3",
    "Kool & The Gang - Ladies Night.mp3",
    "Kylie Minogue - Cant Get You Out Of My Head.mp3",
    "Michael Jackson - Billie Jean.mp3",
    "Orchestral Manoeuvres in the Dark - Enola Gay.mp3",
    "Patrick Hernandez - Born to Be Alive (Original Mix 79).mp3",
    "The Rolling Stones - Good Times (Remastered 2002).mp3",
    "Village People - In the Navy (Original Version 1979).mp3",
    "Village People - YMCA (Original Version 1978).mp3",
    "Yannick - CES SOIREES-LA.mp3",
    "",
    "Music Recorder\\music\\Ma selection Divers",
    " <<artiste>>:Divers_artistes",
    "",
    "Defer et sn orchess - Les pouces en avant (Et tchic et tchac han han).mp3",
    "Happy Birthday - Happy Birthday Metal Instrumental.mp3",
    "La Bande a Basile - La chenille.mp3",
    "Patrick Sebastien - Les sardines.mp3",
    "Zebda - Tomber la chemise.mp3",
    "",
    "Music Recorder\\music\\Ma selection hard rock",
    " <<artiste>>:Divers_artistes",
    "",
    "AC_DC - Back In Black.mp3",
    "AC_DC - Highway to Hell.mp3",
    "AC_DC - Thunderstruck.mp3",
    "Black Sabbath - Paranoid (2009 Remastered Version).mp3",
    "Deep Purple - Smoke On the Water.mp3",
    "Motley Crue - Kickstart My Heart.mp3",
    "The Cranberries - Zombie.mp3",
    "The Survivors - Eye Of Tiger.mp3",
    "Trust - Antisocial.mp3",
    "",
    "Music Recorder\\music\\Ma selection monde",
    " <<artiste>>:Divers_artistes",
    "",
    "Alpha Blondy - Cocody Rock.mp3",
    "Aya Nakamura - Comportement.mp3",
    "Bellini - Samba De Janeiro.mp3",
    "Billy Ze Kick et les Gamins en Folie - Mangez-moi ! Mangez-moi ! (Ragga Mix).mp3",
    "Bob Marley & The Wailers - Get Up_ Stand Up (Live At Leeds 1973).mp3",
    "Chino & Nacho - Tu Me Quemas.mp3",
    "Danakil - Marley.mp3",
    "Dj Assad - Embale li.mp3",
    "Dropkick Murphys - Im Shipping Up To Boston.mp3",
    "Errol Dunkley - OK Fred.mp3",
    "Fito Blanko - Pegadito Suavecito (Radio Mix).mp3",
    "Francky Vincent - Fruit de la passion.mp3",
    "Generation Fete - Un Dos Tres (Maria).mp3",
    "Kaoma - Lambada (Original Version 1989).mp3",
    "King Africa - La Bomba.mp3",
    "Los Lobos - La Bamba.mp3",
    "Lou Bega - Mambo No.5 (A Little Bit Of...) (Radio Edit).mp3",
    "Luis Fonsi - Despacito.mp3",
    "Madness - One Step Beyond (2009 Remaster).mp3",
    "Magic System - Ambiance a lafricaine.mp3",
    "Magic System - Bouger bouger (feat. Mokobe).mp3",
    "Manu Chao - Me Gustas Tu.mp3",
    "Naaman - Karma.mp3",
    "Naaman - Skanking Shoes.mp3",
    "Pierpoljak - Pierpoljak.mp3",
    "Rednex - cotton eye joe.mp3",
    "Scatman John - Scatman (ski-ba-bop-ba-dop-bop).mp3",
    "Shakira - Waka Waka (This Time for Africa) (The Official 2010 FIFA World Cup (TM) Song).mp3",
    "UB40 - Kingston Town.mp3",
    "UB40 - Red Red Wine (Edit).mp3",
    "Will Burnett and His Madison Dance Orchestra - Last Night (Madison).mp3",
    "",
    "Music Recorder\\music\\Ma selection rock",
    " <<artiste>>:Divers_artistes",
    "",
    "AC_DC - You Shook Me All Night Long.mp3",
    "Evanescence - Bring Me To Life.mp3",
    "Green Day - Holiday (Faded Ending).mp3",
    "Iron Maiden - Run to the Hills (1998 Remastered Version).mp3",
    "Judas Priest - Painkiller.mp3",
    "Pretty Boy Floyd - Aint Talking About Love (Razed In Black Remix).mp3",
    "",
    "Music Recorder\\music\\Ma selection Rock2",
    " <<artiste>>:Divers_artistes",
    "",
    "Big Soul - Hippy Hippy Shake.mp3",
    "Blondie - Heart of Glass.mp3",
    "Chuck Berry - You Never Can Tell (1986 Stereo Remix).mp3",
    "Depeche Mode - Enjoy The Silence (Remastered Version Original).mp3",
    "Eagle-Eye Cherry - Save Tonight.mp3",
    "Elmer Food Beat - Daniela.mp3",
    "Europe - The Final Countdown.mp3",
    "INXS - Suicide Blonde.mp3",
    "Joan Jett and the Blackhearts - I Love Rock N Roll.mp3",
    "Les Rita Mitsouko - Cest Comme Ca.mp3",
    "Les Wampas - Manu Chao (Single Version).mp3",
    "Matmatah - Lambe An Dro.mp3",
    "Niagara - Jai vu.mp3",
    "Nirvana - Love Buzz.mp3",
    "Roxette - The Look.mp3",
    "Spin Doctors - Two Princes.mp3",
    "Steppenwolf - Born To Be Wild.mp3",
    "Studio 99 - Sharpe Dressed Man (As Performed by ZZ Top).mp3",
    "Supergrass - Alright.mp3",
    "Telephone - Ca cest vraiment toi.mp3",
    "Telephone - Hygiaphone.mp3",
    "The Cure - Boys Dont Cry.mp3",
    "The Kinks - All Day And All Of The Night.mp3",
    "The Kinks - You Really Got Me (Remastered).mp3",
    "The Rolling Stones - Anybody Seen My Baby_ (Remastered).mp3",
    "The Rolling Stones - Start Me Up (Remastered).mp3",
    "Van Halen - Jump (2015 Remastered Version).mp3",
    "ZZ Top - Gimme All Your Lovin.mp3",
    "",
    "Music Recorder\\music\\Ma selection slow",
    " <<artiste>>:Divers_artistes",
    "",
    "Adele - Someone Like You.mp3",
    "Bee Gees - How Deep Is Your Love.mp3",
    "Billy Paul - Me and Mrs. Jones.mp3",
    "Bryan Adams - (Everything I Do) I Do It For You.mp3",
    "Cyndi Lauper - True Colors.mp3",
    "Foreigner - I Want To Know What Love Is (2008 Remastered Version).mp3",
    "George Michael - Careless Whisper.mp3",
    "George Michael - Jesus to a Child.mp3",
    "Joe Bonamassa - Ill Take Care Of You.mp3",
    "Lionel Richie - Hello.mp3",
    "Marvin Gaye - Sexual Healing.mp3",
    "Phil Collins - Another Day In Paradise (2016 Remastered).mp3",
    "Procol Harum - A Whiter Shade Of Pale.mp3",
    "Santana - Samba Pa Ti.mp3",
    "Scorpions - Still Loving You.mp3",
    "Scorpions - Wind Of Change.mp3",
    "Spandau Ballet - True.mp3",
    "Whitney Houston - I Will Always Love You.mp3",
    ""
]