GET http://localhost:3001/api

###

POST http://localhost:3001/api
Content-Type: application/json

{
    "message": "toto"
}

###

PUT http://localhost:3001/api
Content-Type: application/json

{
    "old_message": "toto",
    "new_message": "tata"
}

###

DELETE http://localhost:3001/api
Content-Type: application/json

{
    "message": "tata"
}
